#define TT_MAKE_TAG(_x1, _x2, _x3, _x4 ) (((uint32_t)_x1 << 24 ) | ((uint32_t)_x2 << 16 ) | ((uint32_t)_x3 <<  8 ) | (uint32_t)_x4)

#define TTAG_avar  TT_MAKE_TAG('a', 'v', 'a', 'r')
#define TTAG_BASE  TT_MAKE_TAG('B', 'A', 'S', 'E')
#define TTAG_bdat  TT_MAKE_TAG('b', 'd', 'a', 't')
#define TTAG_BDF   TT_MAKE_TAG('B', 'D', 'F', ' ')
#define TTAG_bhed  TT_MAKE_TAG('b', 'h', 'e', 'd')
#define TTAG_bloc  TT_MAKE_TAG('b', 'l', 'o', 'c')
#define TTAG_bsln  TT_MAKE_TAG('b', 's', 'l', 'n')
#define TTAG_CBDT  TT_MAKE_TAG('C', 'B', 'D', 'T')
#define TTAG_CBLC  TT_MAKE_TAG('C', 'B', 'L', 'C')
#define TTAG_CFF   TT_MAKE_TAG('C', 'F', 'F', ' ')
#define TTAG_CFF2  TT_MAKE_TAG('C', 'F', 'F', '2')
#define TTAG_CID   TT_MAKE_TAG('C', 'I', 'D', ' ')
#define TTAG_cmap  TT_MAKE_TAG('c', 'm', 'a', 'p')
#define TTAG_COLR  TT_MAKE_TAG('C', 'O', 'L', 'R')
#define TTAG_CPAL  TT_MAKE_TAG('C', 'P', 'A', 'L')
#define TTAG_cvar  TT_MAKE_TAG('c', 'v', 'a', 'r')
#define TTAG_cvt   TT_MAKE_TAG('c', 'v', 't', ' ')
#define TTAG_DSIG  TT_MAKE_TAG('D', 'S', 'I', 'G')
#define TTAG_EBDT  TT_MAKE_TAG('E', 'B', 'D', 'T')
#define TTAG_EBLC  TT_MAKE_TAG('E', 'B', 'L', 'C')
#define TTAG_EBSC  TT_MAKE_TAG('E', 'B', 'S', 'C')
#define TTAG_feat  TT_MAKE_TAG('f', 'e', 'a', 't')
#define TTAG_FFTM  TT_MAKE_TAG('F', 'F', 'T', 'M')
#define TTAG_FOND  TT_MAKE_TAG('F', 'O', 'N', 'D')
#define TTAG_fpgm  TT_MAKE_TAG('f', 'p', 'g', 'm')
#define TTAG_fvar  TT_MAKE_TAG('f', 'v', 'a', 'r')
#define TTAG_gasp  TT_MAKE_TAG('g', 'a', 's', 'p')
#define TTAG_GDEF  TT_MAKE_TAG('G', 'D', 'E', 'F')
#define TTAG_glyf  TT_MAKE_TAG('g', 'l', 'y', 'f')
#define TTAG_GPOS  TT_MAKE_TAG('G', 'P', 'O', 'S')
#define TTAG_GSUB  TT_MAKE_TAG('G', 'S', 'U', 'B')
#define TTAG_gvar  TT_MAKE_TAG('g', 'v', 'a', 'r')
#define TTAG_HVAR  TT_MAKE_TAG('H', 'V', 'A', 'R')
#define TTAG_hdmx  TT_MAKE_TAG('h', 'd', 'm', 'x')
#define TTAG_head  TT_MAKE_TAG('h', 'e', 'a', 'd')
#define TTAG_hhea  TT_MAKE_TAG('h', 'h', 'e', 'a')
#define TTAG_hmtx  TT_MAKE_TAG('h', 'm', 't', 'x')
#define TTAG_JSTF  TT_MAKE_TAG('J', 'S', 'T', 'F')
#define TTAG_just  TT_MAKE_TAG('j', 'u', 's', 't')
#define TTAG_kern  TT_MAKE_TAG('k', 'e', 'r', 'n')
#define TTAG_lcar  TT_MAKE_TAG('l', 'c', 'a', 'r')
#define TTAG_loca  TT_MAKE_TAG('l', 'o', 'c', 'a')
#define TTAG_LTSH  TT_MAKE_TAG('L', 'T', 'S', 'H')
#define TTAG_LWFN  TT_MAKE_TAG('L', 'W', 'F', 'N')
#define TTAG_MATH  TT_MAKE_TAG('M', 'A', 'T', 'H')
#define TTAG_maxp  TT_MAKE_TAG('m', 'a', 'x', 'p')
#define TTAG_META  TT_MAKE_TAG('M', 'E', 'T', 'A')
#define TTAG_MMFX  TT_MAKE_TAG('M', 'M', 'F', 'X')
#define TTAG_MMSD  TT_MAKE_TAG('M', 'M', 'S', 'D')
#define TTAG_mort  TT_MAKE_TAG('m', 'o', 'r', 't')
#define TTAG_morx  TT_MAKE_TAG('m', 'o', 'r', 'x')
#define TTAG_MVAR  TT_MAKE_TAG('M', 'V', 'A', 'R')
#define TTAG_name  TT_MAKE_TAG('n', 'a', 'm', 'e')
#define TTAG_opbd  TT_MAKE_TAG('o', 'p', 'b', 'd')
#define TTAG_OS2   TT_MAKE_TAG('O', 'S', '/', '2')
#define TTAG_OTTO  TT_MAKE_TAG('O', 'T', 'T', 'O')
#define TTAG_PCLT  TT_MAKE_TAG('P', 'C', 'L', 'T')
#define TTAG_POST  TT_MAKE_TAG('P', 'O', 'S', 'T')
#define TTAG_post  TT_MAKE_TAG('p', 'o', 's', 't')
#define TTAG_prep  TT_MAKE_TAG('p', 'r', 'e', 'p')
#define TTAG_prop  TT_MAKE_TAG('p', 'r', 'o', 'p')
#define TTAG_sbix  TT_MAKE_TAG('s', 'b', 'i', 'x')
#define TTAG_sfnt  TT_MAKE_TAG('s', 'f', 'n', 't')
#define TTAG_SING  TT_MAKE_TAG('S', 'I', 'N', 'G')
#define TTAG_trak  TT_MAKE_TAG('t', 'r', 'a', 'k')
#define TTAG_true  TT_MAKE_TAG('t', 'r', 'u', 'e')
#define TTAG_ttc   TT_MAKE_TAG('t', 't', 'c', ' ')
#define TTAG_ttcf  TT_MAKE_TAG('t', 't', 'c', 'f')
#define TTAG_TYP1  TT_MAKE_TAG('T', 'Y', 'P', '1')
#define TTAG_typ1  TT_MAKE_TAG('t', 'y', 'p', '1')
#define TTAG_VDMX  TT_MAKE_TAG('V', 'D', 'M', 'X')
#define TTAG_vhea  TT_MAKE_TAG('v', 'h', 'e', 'a')
#define TTAG_vmtx  TT_MAKE_TAG('v', 'm', 't', 'x')
#define TTAG_VVAR  TT_MAKE_TAG('V', 'V', 'A', 'R')
#define TTAG_wOFF  TT_MAKE_TAG('w', 'O', 'F', 'F')
